### ISSUE TITLE
The datasets can be downloaded separately here.

### ISSUE THREAD

**Issue by lili1234567890** [ccsasuke/adan#1]
The link can't be opened, can you share the URL?

**Comment by ccsasuke** [comment]
It seems the link works fine for me. Could you double check? Also, the link is on Dropbox, which is not accessible from China, so you may want to try using a VPN if you are from there.

And FYI, the full URL is: https://www.dropbox.com/sh/zlnjcrc6l9zlry4/AAApYaSz9PvESc5xMiAKD_Jka?dl=0

**Comment by lili1234567890** [comment]
Yes, I am in China, I understand
