### ISSUE TITLE
Question: Are the embeddings updated during training?

### ISSUE THREAD

**Issue by JoaoLages** [ccsasuke/adan#3]
Are the embeddings updated or are they frozen? Since you are using multilingual embeddings, seems to me that the model would better adapt the weights of F to different languages if you wouldn't update the embedding space

**Comment by ccsasuke** [comment]
We update the embeddings during training.
There is an option to fix embeddings during training:
https://github.com/ccsasuke/adan/blob/d65794bf8ea6f706c263a037ba99280cdd55c07e/code/options.py#L20

Feel free to try it out. I vaguely remember that it gave worse results.
